# -*- coding: utf-8 -*-
"""Training Model CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16yuCPP_TUUQM8q_x5NhbYD0Gjoqx3cjw

#***1. menyiapkan library & dataset untuk ditraining, & menghubungkan ke drive***
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models, callbacks
import matplotlib.pyplot as plt
import os

# GANTI PATH INI jika Anda menaruh folder di dalam sub-folder lain
# Jika folder 'dataset_skripsi' ada di halaman depan Drive, biarkan seperti ini:
base_dir = '/content/drive/MyDrive/Colab Notebooks/dataset_skripsi'

# Cek apakah folder terbaca
if os.path.exists(base_dir):
    print("✅ Folder dataset ditemukan!")
    print("Isi folder:", os.listdir(base_dir))
else:
    print("❌ Folder tidak ditemukan. Cek nama folder di Google Drive Anda!")

"""#***2.Preprocessing & Augmentasi Data***"""

# Kita perbanyak data secara buatan agar AI lebih pintar (Rotation, Zoom, Flip)
train_datagen = ImageDataGenerator(
    rescale=1./255,         # Normalisasi warna (0-255 jadi 0-1)
    rotation_range=30,      # Putar gambar hingga 30 derajat
    width_shift_range=0.2,  # Geser kiri-kanan
    height_shift_range=0.2, # Geser atas-bawah
    shear_range=0.2,        # Miringkan gambar
    zoom_range=0.2,         # Zoom in/out
    horizontal_flip=True,   # Balik horizontal
    fill_mode='nearest',
    validation_split=0.2    # 20% data diambil untuk Ujian (Validasi)
)

print("\nMenyiapkan Data Latih (Training)...")
train_generator = train_datagen.flow_from_directory(
    base_dir,
    target_size=(224, 224), # Ukuran standar MobileNetV2
    batch_size=32,
    class_mode='categorical',
    subset='training',
    shuffle=True
)

print("\nMenyiapkan Data Uji (Validation)...")
validation_generator = train_datagen.flow_from_directory(
    base_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='validation',
    shuffle=False
)

# Tampilkan Label Kelas (Penting untuk nanti bikin aplikasi)
class_names = list(train_generator.class_indices.keys())
print("\nLabel Kelas yang dideteksi:", class_names)
print(f"Total Kelas: {len(class_names)}")

"""#***3. Membangun Model***

"""

base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False # Bekukan otak utama agar tidak rusak saat latihan awal

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.3), # Membuang 30% neuron acak agar tidak menghafal (Overfitting)
    layers.Dense(256, activation='relu'),
    layers.Dense(len(class_names), activation='softmax') # Output layer otomatis sesuai jumlah folder (8)
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

"""#***4. Melakukan Trainig Data***"""

early_stop = callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

print("\n🚀 Mulai Melatih Model AI... (Sabar ya, ini butuh waktu)")
history = model.fit(
    train_generator,
    epochs=20,  # Lakukan 20 putaran (bisa diubah jadi 30-50 jika kurang puas)
    validation_data=validation_generator,
    callbacks=[early_stop]
)

"""#***5. Evaluasi Model***"""

save_dir = '/content/drive/MyDrive/dataset_skripsi'
model_filename = 'model_padi_komplit.h5'
model_path = os.path.join(save_dir, model_filename)

# Plot Grafik Akurasi (Tetap ditampilkan buat laporan)
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Grafik Akurasi')

plt.subplot(1, 2, 2)
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Grafik Loss (Error)')
plt.show()

# 2. Simpan Model
print(f"💾 Sedang menyimpan model ke: {model_path} ...")
model.save(model_path)
print("\n✅ BERHASIL! Model sudah tersimpan di Google Drive Anda.")
print("Silakan cek folder Google Drive 'dataset_skripsi', file .h5 pasti sudah ada di sana.")